   services:
     app:
       image: devilbox/php-fpm:8.2-work
       container_name: csv_to_mail_api_app
       restart: always
       volumes:
         - ../csv_to_mail_api:/var/www/html
       working_dir: /var/www/html
       networks:
         - csv_to_mail_api_network
       depends_on:
         - postgres

     webserver:
       image: nginx:alpine
       container_name: csv_to_mail_api_webserver
       restart: always
       volumes:
         - ../csv_to_mail_api:/var/www/html
         - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
       ports:
         - "80:80"
       networks:
         - csv_to_mail_api_network

     postgres:
       image: postgres:latest
       container_name: csv_to_mail_api_postgres
       restart: always
       environment:
         POSTGRES_USER: user2
         POSTGRES_PASSWORD: password2
         POSTGRES_DB: csv_to_mail_api_db2
       ports:
         - "5444:5432"
       volumes:
         - postgres_csv_to_mail:/var/lib/postgresql/data
       networks:
         - csv_to_mail_api_network

   networks:
     csv_to_mail_api_network:
       driver: bridge

   volumes:
     postgres_csv_to_mail: